### ISSUE TITLE
Tweak does not work

### ISSUE THREAD

**Issue by AnhNguyenlost13** [m4fn3/K2genmity#1]
iPhone 7
iOS version: 15.8.0
Plug-in version: 1.3.7
Rosiecord 223.0

- I've double checked that Choicy does not prevent the tweak from being injected
- I am using Dopamine rootless

**Comment by m4fn3** [comment]
It's confirmed that the tweak is being broken on newer
versions for a while.

2024年6月7日(金) 22:36 AnhNguyenlost13 ***@***.***>:
